name: build-test

on:
  push:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

  pull_request:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

jobs:
  gen-matrix:
    name: generate-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate file differences
        id: diff
        uses: tj-actions/changed-files@v45
        with:
          json: true
          escape_json: false

      - name: Generate testing matrix
        uses: actions/github-script@v7
        id: generator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/genMatrix.js`)
            return script(
              ${{ steps.diff.outputs.added_files }},
              ${{ steps.diff.outputs.modified_files }},
              ${{ steps.diff.outputs.renamed_files }},
            );

    outputs:
      matrix: ${{ steps.generator.outputs.result }}

  build:
    if: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    needs: gen-matrix
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    env:
      NODE_VERSION: ${{ matrix.version }}
      IMAGE_TAG: node:${{ matrix.version }}-${{ matrix.variant }}

    steps:
      - name: Get short node version
        uses: actions/github-script@v7
        id: short-version
        with:
          result-encoding: string
          script: return "${{ matrix.version }}".split('.')[0]

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          context: ./${{ steps.short-version.outputs.result }}/${{ matrix.variant }}
          tags: ${{ env.IMAGE_TAG }}

      - name: Run tests with BATS
        run: npx bats@1.6.0 --verbose-run test/docker-image.bats
